name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Update kubeconfig
      run: aws eks --region us-west-2 update-kubeconfig --name kaiszn-cluster

    - name: Pull Docker image
      run: docker pull your-dockerhub-username/kaiszn-cloudcommerce-app:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/kaiszn-cloudcommerce-app kaiszn-cloudcommerce-app=your-dockerhub-username/kaiszn-cloudcommerce-app:latest
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/secret.yaml
